"""Generate the deterministic KVL corpus: files, register CSVs, links and ground truth.

    python -m dcc_corpus.generate --out corpus --seed 1905
"""

import argparse
import csv
import hashlib
import shutil
from pathlib import Path

from dcc_corpus import naming
from dcc_corpus.render import RENDERERS
from dcc_corpus.render.common import RenderContext
from dcc_corpus.spec import TEMPLATE_FORMATS, load_spec, split_target, validate

DEFAULT_SEED = 1905
# Everything the generator owns inside the output folder; nothing else is touched.
GENERATED = ["KVL Project", "register", "ground_truth", "links.csv", "README.md"]

TABLES = {
    "register/wbs.csv": ["code", "name", "parent_code", "aliases"],
    "register/organisations.csv": ["code", "name", "role", "aliases"],
    "register/people.csv": ["name", "org_code", "title"],
    "register/documents.csv": ["doc_code", "title", "wbs_code", "discipline_code", "doc_type_code",
                               "originator_code", "owner_name"],
    "register/revisions.csv": ["doc_code", "rev_code", "revision_date", "stage_code", "sender_code", "description"],
    "register/revision_status.csv": ["doc_code", "rev_code", "status_code", "effective_date", "assigned_by_code", "note"],
    "register/revision_files.csv": ["doc_code", "rev_code", "copy_role", "filename", "original_location",
                                    "storage_path", "file_format", "size_bytes", "sha256"],
    "links.csv": ["from_doc_code", "from_rev_code", "to_doc_code", "to_rev_code", "link_type", "provenance", "note"],
    "ground_truth/threads.csv": ["storyline", "storyline_name", "doc_code"],
    "ground_truth/planted_cases.csv": ["case", "doc_code", "rev_code", "note"],
}

README = """# DCC V1 synthetic corpus

Generated by `python -m dcc_corpus.generate` from `dcc_corpus/spec/`. Do not edit by hand.

Everything here is fictional: the Kestrel Valley Link Road project, its organisations, people,
documents and engineering values. Document codes follow the KVL project convention, which is
inspired by ISO 19650 concepts but is not the ISO 19650 naming convention.

- `KVL Project/` - the simulated project share (original file locations)
- `register/` - registered metadata: WBS, organisations, people, documents, revisions,
  status history, files
- `links.csv` - registered relationships between documents and revisions
- `ground_truth/` - storyline membership and planted cases, for evaluation only;
  never loaded into the application database
"""


def generate(out: Path, seed: int = DEFAULT_SEED) -> dict[str, list[dict]]:
    project, timeline = load_spec()
    errors = validate(project, timeline)
    if errors:
        raise ValueError("spec is invalid:\n" + "\n".join(errors))

    out.mkdir(parents=True, exist_ok=True)
    for name in GENERATED:
        target = out / name
        if target.is_dir():
            shutil.rmtree(target)
        elif target.exists():
            target.unlink()

    wbs_folders = {w["code"]: f"{w['code']} {w['name']}" for w in project["wbs"]}
    documents = timeline["documents"]
    tables = {name: [] for name in TABLES}
    history: dict[str, list] = {key: [] for key in documents}

    # Reference data, so the register is self-contained; aliases are "|"-separated.
    for w in project["wbs"]:
        tables["register/wbs.csv"].append({"code": w["code"], "name": w["name"], "parent_code": w.get("parent", ""),
                                           "aliases": "|".join(w.get("aliases", []))})
    for o in project["organisations"]:
        tables["register/organisations.csv"].append({"code": o["code"], "name": o["name"], "role": o["role"],
                                                     "aliases": "|".join(o.get("aliases", []))})
    for p in project["people"]:
        tables["register/people.csv"].append({"name": p["name"], "org_code": p["org"], "title": p["title"]})

    for doc in documents.values():
        code = naming.parse_doc_code(doc["doc_code"])
        tables["register/documents.csv"].append({
            "doc_code": doc["doc_code"], "title": doc["title"], "wbs_code": code.wbs,
            "discipline_code": code.discipline, "doc_type_code": code.doc_type,
            "originator_code": code.originator, "owner_name": doc["owner"],
        })
        tables["ground_truth/threads.csv"].append(
            {"storyline": timeline["storyline"], "storyline_name": timeline["name"], "doc_code": doc["doc_code"]})

    for event in timeline["events"]:
        when = event["date"]
        for item in event.get("issue", []):
            doc = documents[item["doc"]]
            code = naming.parse_doc_code(doc["doc_code"])
            rev = item["rev"]
            history[item["doc"]].append((rev, when, item["description"]))
            tables["register/revisions.csv"].append({
                "doc_code": doc["doc_code"], "rev_code": rev, "revision_date": when.isoformat(),
                "stage_code": item["stage"], "sender_code": "", "description": item["description"],
            })
            tables["register/revision_status.csv"].append({
                "doc_code": doc["doc_code"], "rev_code": rev, "status_code": item["status"],
                "effective_date": when.isoformat(), "assigned_by_code": code.originator, "note": "",
            })

            ext = TEMPLATE_FORMATS[doc["template"]]
            filename = item.get("filename") or naming.build_filename(code, rev, doc["title"], ext)
            location = naming.standard_location(code.doc_type, wbs_folders[code.wbs], code.originator, when)
            if item.get("filed") == "superseded":
                location = naming.superseded_location(location)
            path = out / location / filename
            path.parent.mkdir(parents=True, exist_ok=True)
            RENDERERS[doc["template"]](path, RenderContext(
                project=project, doc=doc, rev=rev, issued=when, status=item["status"], stage=item["stage"],
                description=item["description"], content=item.get("content", {}),
                history=list(history[item["doc"]]), seed=seed,
            ))

            files = [("primary", location)] + [("copy", c["location"]) for c in item.get("copies", [])]
            for role, folder in files:
                copy_path = out / folder / filename
                if role == "copy":
                    copy_path.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copyfile(path, copy_path)
                data = copy_path.read_bytes()
                tables["register/revision_files.csv"].append({
                    "doc_code": doc["doc_code"], "rev_code": rev, "copy_role": role, "filename": filename,
                    "original_location": folder, "storage_path": f"{folder}/{filename}", "file_format": ext,
                    "size_bytes": len(data), "sha256": hashlib.sha256(data).hexdigest(),
                })

        for change in event.get("status_change", []):
            tables["register/revision_status.csv"].append({
                "doc_code": documents[change["doc"]]["doc_code"], "rev_code": change["rev"],
                "status_code": change["status"], "effective_date": when.isoformat(),
                "assigned_by_code": change["by"], "note": change.get("note", ""),
            })

    def resolve(target: str) -> tuple[str, str]:
        key, rev = split_target(target)
        return documents[key]["doc_code"], rev or ""

    for link in timeline.get("links", []):
        (from_code, from_rev), (to_code, to_rev) = resolve(link["from"]), resolve(link["to"])
        tables["links.csv"].append({
            "from_doc_code": from_code, "from_rev_code": from_rev, "to_doc_code": to_code, "to_rev_code": to_rev,
            "link_type": link["type"], "provenance": "registered", "note": link.get("note", ""),
        })
    for case in timeline.get("planted", []):
        doc_code, rev = resolve(case["target"])
        tables["ground_truth/planted_cases.csv"].append(
            {"case": case["case"], "doc_code": doc_code, "rev_code": rev, "note": case["note"]})

    for name, rows in tables.items():
        target = out / name
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=TABLES[name], lineterminator="\n")
            writer.writeheader()
            writer.writerows(rows)
    (out / "README.md").write_text(README, encoding="utf-8", newline="\n")
    return tables


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=Path("corpus"))
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    args = parser.parse_args()
    tables = generate(args.out, args.seed)
    files = tables["register/revision_files.csv"]
    print(f"Generated {len(files)} files, {len(tables['register/revisions.csv'])} revisions, "
          f"{len(tables['register/documents.csv'])} documents into {args.out}")


if __name__ == "__main__":
    main()
